import { IndicadorProps, PaisProps } from "../types";

export const indicadores:IndicadorProps[] = [
    {id:77818,nome:"Economia - Chegada de turistas"},
    {id:77819,nome:"Economia - Gastos públicos com educação"},
    {id:77820,nome:"Economia - Gastos públicos com saúde"},
    {id:77821,nome:"Economia - Investimentos em pesquisa e desenvolvimento"},
    {id:77822,nome:"Economia - Mulheres de 15 anos ou mais de idade economicamente ativas"},
    {id:77823,nome:"Economia - PIB per capita"},
    {id:77824,nome:"Economia - População de 15 anos ou mais de idade economicamente ativa"},
    {id:77825,nome:"Economia - Total de exportações"},
    {id:77826,nome:"Economia - Total de importações"},
    {id:77827,nome:"Economia - Total do PIB"},
    {id:77830,nome:"Indicadores sociais - Esperança de vida ao nascer"},
    {id:77831,nome:"Indicadores sociais - Índice de desenvolvimento humano"},
    {id:77832,nome:"Indicadores sociais - População com acesso à água potável"},
    {id:77833,nome:"Indicadores sociais - População com acesso à rede sanitária"},
    {id:77835,nome:"Indicadores sociais - Taxa bruta de matrículas para todos os níveis de ensino"},
    {id:77836,nome:"Indicadores sociais - Taxa de alfabetização das pessoas de 15 anos ou mais de idade"},
    {id:77838,nome:"Meio Ambiente - Áreas cultivadas"},
    {id:77839,nome:"Meio Ambiente - Áreas de pastagens permanentes"},
    {id:77840,nome:"Meio Ambiente - Áreas protegidas no total do território nacional"},
    {id:77841,nome:"Meio Ambiente - Produção de gás natural"},
    {id:77842,nome:"Meio Ambiente - Produção de petróleo"},
    {id:77844,nome:"População - Densidade demográfica"},
    {id:77845,nome:"População - Homens"},
    {id:77846,nome:"População - Mulheres"},
    {id:77847,nome:"População - População residente em área rural"},
    {id:77848,nome:"População - População residente em área urbana"},
    {id:77849,nome:"População - População"},
    {id:77850,nome:"População - Taxa bruta de mortalidade"},
    {id:77851,nome:"População - Taxa bruta de natalidade"},
    {id:77852,nome:"População - Taxa média anual do crescimento da população"},
    {id:77854,nome:"Redes - Assinaturas de telefonia celular"},
    {id:77855,nome:"Redes - Assinaturas de telefonia fixa"},
    {id:77857,nome:"Redes - Indivíduos com acesso à internet"},
    {id:77829,nome:"Saúde - Consumo calórico"},
    {id:77834,nome:"Saúde - Incidência de subnutrição"}
];

export const paises: PaisProps[] = [
    { id: "AF", nome: "Afeganistão" },
    { id: "ZA", nome: "África do Sul" },
    { id: "AL", nome: "Albânia" },
    { id: "DE", nome: "Alemanha" },
    { id: "AD", nome: "Andorra" },
    { id: "AO", nome: "Angola" },
    { id: "AG", nome: "Antígua e Barbuda" },
    { id: "SA", nome: "Arábia Saudita" },
    { id: "DZ", nome: "Argélia" },
    { id: "AR", nome: "Argentina" },
    { id: "AM", nome: "Armênia" },
    { id: "AU", nome: "Austrália" },
    { id: "AT", nome: "Áustria" },
    { id: "AZ", nome: "Azerbaijão" },
    { id: "BS", nome: "Bahamas" },
    { id: "BD", nome: "Bangladesh" },
    { id: "BB", nome: "Barbados" },
    { id: "BH", nome: "Barein" },
    { id: "BY", nome: "Belarus" },
    { id: "BE", nome: "Bélgica" },
    { id: "BZ", nome: "Belize" },
    { id: "BJ", nome: "Benin" },
    { id: "BO", nome: "Bolívia" },
    { id: "BA", nome: "Bósnia e Herzegovina" },
    { id: "BW", nome: "Botsuana" },
    { id: "BR", nome: "Brasil" },
    { id: "BN", nome: "Brunei" },
    { id: "BG", nome: "Bulgária" },
    { id: "BF", nome: "Burkina Faso" },
    { id: "BI", nome: "Burundi" },
    { id: "BT", nome: "Butão" },
    { id: "CV", nome: "Cabo Verde" },
    { id: "CM", nome: "Camarões" },
    { id: "KH", nome: "Camboja" },
    { id: "CA", nome: "Canadá" },
    { id: "QA", nome: "Catar" },
    { id: "KZ", nome: "Cazaquistão" },
    { id: "TD", nome: "Chade" },
    { id: "CL", nome: "Chile" },
    { id: "CN", nome: "China" },
    { id: "CY", nome: "Chipre" },
    { id: "CO", nome: "Colômbia" },
    { id: "KM", nome: "Comores" },
    { id: "CG", nome: "Congo" },
    { id: "CI", nome: "Costa do Marfim" },
    { id: "CR", nome: "Costa Rica" },
    { id: "HR", nome: "Croácia" },
    { id: "CU", nome: "Cuba" },
    { id: "DK", nome: "Dinamarca" },
    { id: "DJ", nome: "Djibouti" },
    { id: "DM", nome: "Dominica" },
    { id: "EG", nome: "Egito" },
    { id: "SV", nome: "El Salvador" },
    { id: "AE", nome: "Emirados Árabes Unidos" },
    { id: "EC", nome: "Equador" },
    { id: "ER", nome: "Eritréia" },
    { id: "SK", nome: "Eslováquia" },
    { id: "SI", nome: "Eslovênia" },
    { id: "ES", nome: "Espanha" },
    { id: "US", nome: "Estados Unidos da América" },
    { id: "EE", nome: "Estônia" },
    { id: "SZ", nome: "Eswatini" },
    { id: "ET", nome: "Etiópia" },
    { id: "FJ", nome: "Fiji" },
    { id: "PH", nome: "Filipinas" },
    { id: "FI", nome: "Finlândia" },
    { id: "FR", nome: "França" },
    { id: "GA", nome: "Gabão" },
    { id: "GM", nome: "Gâmbia" },
    { id: "GH", nome: "Gana" },
    { id: "GE", nome: "Geórgia" },
    { id: "GD", nome: "Granada" },
    { id: "GR", nome: "Grécia" },
    { id: "GT", nome: "Guatemala" },
    { id: "GY", nome: "Guiana" },
    { id: "GN", nome: "Guiné" },
    { id: "GQ", nome: "Guiné Equatorial" },
    { id: "GW", nome: "Guiné" },
    { id: "HT", nome: "Haiti" },
    { id: "NL", nome: "Holanda" },
    { id: "HN", nome: "Honduras" },
    { id: "HU", nome: "Hungria" },
    { id: "YE", nome: "Iêmen" },
    { id: "MH", nome: "Ilhas Marshall" },
    { id: "SB", nome: "Ilhas Salomão" },
    { id: "IN", nome: "Índia" },
    { id: "ID", nome: "Indonésia" },
    { id: "IR", nome: "Irã" },
    { id: "IQ", nome: "Iraque" },
    { id: "IE", nome: "Irlanda" },
    { id: "IS", nome: "Islândia" },
    { id: "IL", nome: "Israel" },
    { id: "IT", nome: "Itália" },
    { id: "JM", nome: "Jamaica" },
    { id: "JP", nome: "Japão" },
    { id: "JO", nome: "Jordânia" },
    { id: "KI", nome: "Kiribati" },
    { id: "KW", nome: "Kuwait" },
    { id: "LA", nome: "Laos" },
    { id: "LS", nome: "Lesoto" },
    { id: "LV", nome: "Letônia" },
    { id: "LB", nome: "Líbano" },
    { id: "LR", nome: "Libéria" },
    { id: "LY", nome: "Líbia" },
    { id: "LI", nome: "Liechtenstein" },
    { id: "LT", nome: "Lituânia" },
    { id: "LU", nome: "Luxemburgo" },
    { id: "MK", nome: "Macedônia do Norte" },
    { id: "MG", nome: "Madagáscar" },
    { id: "MY", nome: "Malásia" },
    { id: "MW", nome: "Malauí" },
    { id: "MV", nome: "Maldivas" },
    { id: "ML", nome: "Mali" },
    { id: "MT", nome: "Malta" },
    { id: "MA", nome: "Marrocos" },
    { id: "MU", nome: "Maurício" },
    { id: "MR", nome: "Mauritânia" },
    { id: "MX", nome: "México" },
    { id: "MM", nome: "Mianmar" },
    { id: "FM", nome: "Micronésia" },
    { id: "MZ", nome: "Moçambique" },
    { id: "MD", nome: "Moldávia" },
    { id: "MC", nome: "Mônaco" },
    { id: "MN", nome: "Mongólia" },
    { id: "ME", nome: "Montenegro" },
    { id: "NA", nome: "Namíbia" },
    { id: "NR", nome: "Nauru" },
    { id: "NP", nome: "Nepal" },
    { id: "NI", nome: "Nicarágua" },
    { id: "NE", nome: "Níger" },
    { id: "NG", nome: "Nigéria" },
    { id: "NO", nome: "Noruega" },
    { id: "NZ", nome: "Nova Zelândia" },
    { id: "OM", nome: "Omã" },
    { id: "PW", nome: "Palau" },
    { id: "PA", nome: "Panamá" },
    { id: "PG", nome: "Papua Nova Guiné" },
    { id: "PK", nome: "Paquistão" },
    { id: "PY", nome: "Paraguai" },
    { id: "PE", nome: "Peru" },
    { id: "PL", nome: "Polônia" },
    { id: "PT", nome: "Portugal" },
    { id: "KE", nome: "Quênia" },
    { id: "KG", nome: "Quirguistão" },
    { id: "GB", nome: "Reino Unido" },
    { id: "CF", nome: "República Centro Africana" },
    { id: "KR", nome: "República da Coréia" },
    { id: "CD", nome: "República Democrática do Congo" },
    { id: "DO", nome: "República Dominicana" },
    { id: "KP", nome: "República Popular Democrática da Coréia" },
    { id: "CZ", nome: "República Tcheca" },
    { id: "RO", nome: "Romênia" },
    { id: "RW", nome: "Ruanda" },
    { id: "RU", nome: "Rússia (Federação Russa)" },
    { id: "WS", nome: "Samoa" },
    { id: "SM", nome: "San Marino" },
    { id: "LC", nome: "Santa Lúcia" },
    { id: "KN", nome: "São Cristóvão e Nevis" },
    { id: "ST", nome: "São Tomé e Príncipe" },
    { id: "VC", nome: "São Vicente e Granadinas" },
    { id: "SC", nome: "Seichelles" },
    { id: "SN", nome: "Senegal" },
    { id: "SL", nome: "Serra Leoa" },
    { id: "RS", nome: "Sérvia" },
    { id: "SG", nome: "Singapura" },
    { id: "SY", nome: "Síria" },
    { id: "SO", nome: "Somália" },
    { id: "LK", nome: "Sri Lanka" },
    { id: "SD", nome: "Sudão" },
    { id: "SS", nome: "Sudão do Sul" },
    { id: "SE", nome: "Suécia" },
    { id: "CH", nome: "Suíça" },
    { id: "SR", nome: "Suriname" },
    { id: "TJ", nome: "Tadjiquistão" },
    { id: "TH", nome: "Tailândia" },
    { id: "TZ", nome: "Tanzânia" },
    { id: "TL", nome: "Timor Leste" },
    { id: "TG", nome: "Togo" },
    { id: "TO", nome: "Tonga" },
    { id: "TT", nome: "Trinidad e Tobago" },
    { id: "TN", nome: "Tunísia" },
    { id: "TM", nome: "Turcomenistão" },
    { id: "TR", nome: "Turquia" },
    { id: "TV", nome: "Tuvalu" },
    { id: "UA", nome: "Ucrânia" },
    { id: "UG", nome: "Uganda" },
    { id: "UY", nome: "Uruguai" },
    { id: "UZ", nome: "Uzbequistão" },
    { id: "VU", nome: "Vanuatu" },
    { id: "VE", nome: "Venezuela" },
    { id: "VN", nome: "Vietnã" },
    { id: "ZM", nome: "Zâmbia" },
    { id: "ZW", nome: "Zimbábue" }
];